version: '3'

services:
  app:
    image: edge-betting
    build:
      context: .
      dockerfile: Containerfile.local
    ports: 
      - 3000:3000
    volumes:
      - ./app:/app/app
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles