import { getProviders, signIn } from "next-auth/react";
import Head from "next/head";
import SignInComponent from './SignInComponent'

async function SignIn() {

    const providers = await getProviders();

    return (
      <>
      <Head>
        <title>Next.js OpenShift Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="2xl:container flex m-auto pt-10 justify-center">
          <div className="relative lg:w-6/12 bg-[#070D0D] rounded-xl shadow-lg border border-gray-700 border-dashed">
            <SignInComponent providers={providers} />
          </div>
        </div>
      </>
    )
  }
  
  export default SignIn
//   export async function getServerSideProps() {
//     const providers = await getProviders()
//     return {
//       props: { providers },
//     }
//   }